### ISSUE TITLE
Failed Install - Version 20240626 (Latest)

### ISSUE THREAD

**Issue by chriscrandell** [MrJackSpade/RG35XXP-XFCE#10]
Attempted to install after adding the files to the APPS folder. It will enter the Loading... screen and after around 30-60 seconds it will show a new screen saying Exiting...

Not sure if it's a quick fix but I'm going to dive into the code this week and see if there is a new change preventing it from executing successfully. Hoping the owner knows a quick fix.

**Comment by MrJackSpade** [comment]
I'm not aware of anything, but if you find a fix feel free to submit it here and I'll merge it in

**Comment by joemck** [comment]
FIX: Edit install_xfce.sh, go to line 29, "apt-get install -y imagemagick fbi". Add a new line BEFORE that and put "apt-get update" there.

As-is, it makes an "install-xfce.log" file in the APPS folder, but it only contains "Starting" and "Failed to install imagemagick". So I edited install_xcfe.sh and added ">> $log 2>&1" to the end of the apt-get command on line 29 so I could see what's going wrong. The problem was Ubuntu updating stuff since when the stale package list that's included in the repository was downloaded, not anything Anbernic changed.

I got it to install on the latest 1.0.6 16 GB firmware from Anbernic's site, but I haven't got it to run yet. Now when I select XFCE from the apps menu, it flashes "Loading" and then "Exiting" and back to the app list.

EDIT: It doesn't run because the 16 GB image only gives a 2 GB "Roms" partition and it's already halfway full with the swapfile, resource images and console BIOSes. The installer ran out of space (but didn't show any visible signs that anything was wrong), and XFCE.sh didn't do anything because it was 0 bytes.

I finally got XFCE on Anbernic's 1.0.6 16 GB image by expanding it manually using Ubuntu. It's annoying because Anbernic put the Roms partition at the start, with the system ones after it. The "correct" way would be to move all the system partitions down to the end and then expand Roms. But I had used a big SD and losing a couple GB doesn't matter, so I simply moved Roms to start after the system partitions while still being the first entry in the GPT, and expanded it there. Then I reran the install script. It finished and now I can run XFCE. It looks pretty but I can't interact with it, I think I'll need to get some way to connect (or pair?) a proper keyboard and mouse for that.

**Comment by MrJackSpade** [comment]
The scripts have been updated and this is no longer applicable
