### ISSUE TITLE
Display driver question

### ISSUE THREAD

**Issue by Sucharek233** [MrJackSpade/RG35XXP-XFCE#13]
I don't own the RG35XXP, but I have a question about how the display driver is handeled.

I own an R36S (running ArkOS) and the driver isn't included in the system, so I have to install it. In your scripts, I didn't really find one. Is it not necessary to install one? And also, is the driver accelerated?

**Comment by MrJackSpade** [comment]
Take this with a grain of salt because its been a while since I wrote this and I forget a lot of what I looked at...

The script as written, leverages the existing display setup. As a result though, its not accelerated. I'm pretty sure everything falls back to using the framebuffer directly for rendering through X.

I don't know how the RS36 functions but the stock RG35XX is literally just Ubuntu with a dmenu wrapper, so a lot of stuff "just works". I had tried digging in to the hardware acceleration for some things but basically everything fails, and IIRC thats because Anbernic actually uses private custom branches for all of their hardware accelerated software, specifically so they can try and keep all of the graphics stuff obfuscated. 

This is just me trying to remember conversations I had with other devs like 6 months ago, and I don't know whats changed since then

**Comment by Sucharek233** [comment]
Ok, thats interesting.

R36S uses SDL. There was no X driver preinstalled, so I found another person that found one. Then I also found out that I can get it through a package. And ArkOS is also based on ubuntu, so I can just install anything with apt.

Well, maybe the display driver is different from the one provided in ubuntu packages. And because the RG35XXP and R36S have the same gpu, maybe they'll be compatible. It should be in `/usr/lib/xorg/modules/drivers/`. If there's a driver file (or files), could you share them with me?

But as you said, no acceleration, so I'll probably get the same result as with the drivers I already have.
