### ISSUE TITLE
Access to Linux System / Package Manager?

### ISSUE THREAD

**Issue by DrKlipper** [MrJackSpade/RG35XXP-XFCE#14]
Hi !
This question is more related to the core Linux system. 
Is there any direct access / login possible - maybe even root access? 
Is there any package manager to install other stuff - python would be awesome ... 
And which base system did they use? Something debian based? 

Would be great if you know some details. 

Thx Dominik

**Comment by MrJackSpade** [comment]
> Is there any direct access / login possible - maybe even root access?
`root:root`

Theres also supposed to be a login `game:game`, but I was never able to get that working, so everything is on root

> Is there any package manager to install other stuff - python would be awesome ...

apt is installed as well as python. I don't remember if pip is installed in the current image, but it will be in the new one. I think in both the new and old image, apt is set up to use the official Ubuntu repositories, although the selection is light because the architecture is arm:hf

> And which base system did they use? Something debian based?

Ubuntu 22.04

**Comment by DrKlipper** [comment]
Thx for those details. 
That sound promising :-) Just have to get one of these devices ....

Did you know if the new devices like rg-40xxv have the same architecture ?

**Comment by MrJackSpade** [comment]
It looks very similar. The same scripts might actually work without modification

**Comment by DrKlipper** [comment]
Thx for your reply. 
I really need to get my hands on such a device 😄
