### ISSUE TITLE
How did you fix the audio?

### ISSUE THREAD

**Issue by Horuhin** [MrJackSpade/RG35XXP-XFCE#15]
Hi, let me start saying that I appreciate your hard high quality work 
I don't own the RG35XXP but the R36S. Some person adapted your scripts to run in the R36S but the project has been stale for a while. (https://github.com/OkJacket2022/R36S-Xorg)
I see you achieved to fix the audio but can't seem to understand how. I checked xinitrc and it seems that you kill pulseaudio and then redirect it so the desktop environment can pipeline the audio through it. I tried doing the same on my Launch_LXDE script to not avail.

Was a driver change necessary on some step? This is the only barrier between me and some cool RPG Maker MV games

Thank you in advance

**Comment by MrJackSpade** [comment]
1. Update the pulseaudio configuration to allow unauthenticated access (because root)

https://github.com/MrJackSpade/RG35XXP-XFCE/blob/aac9022f8568d1424da6825209cc98ca0fd10dee/payload/home/root/setup/run_me.sh#L135

2. Kill any existing instances

https://github.com/MrJackSpade/RG35XXP-XFCE/blob/aac9022f8568d1424da6825209cc98ca0fd10dee/payload/etc/X11/xinit/xinitrc#L2

3. Restart the server as a daemon, without the ability to be killed (so XFCE doesn't restart it)

https://github.com/MrJackSpade/RG35XXP-XFCE/blob/aac9022f8568d1424da6825209cc98ca0fd10dee/payload/etc/X11/xinit/xinitrc#L3

4. (Attempt to) Set the default output sink to the correct hardware

https://github.com/MrJackSpade/RG35XXP-XFCE/blob/aac9022f8568d1424da6825209cc98ca0fd10dee/payload/etc/X11/xinit/xinitrc#L4

**Comment by Horuhin** [comment]
Thank you for the info! This will surely help
