### ISSUE TITLE
OS partition space goes full

### ISSUE THREAD

**Issue by kasra9400** [MrJackSpade/RG35XXP-XFCE#16]
i have a 64gb sdcard and flashed the original OS on it. now i have 43gb space on ROMS and 7.4gb on os partition.
the problem is the OS partition goes full really fast after installing few apps.
is there any way to resize this partition or install apps on somewhere else?

**Comment by MrJackSpade** [comment]
Which version of the firmware are you using?

The partitions can be resized, it just gets a little complicated depending on the layout.

**Comment by kasra9400** [comment]
> Which version of the firmware are you using?
> 
> The partitions can be resized, it just gets a little complicated depending on the layout.

im using 1.1.6 stock MOD.
are the partitions different from the normal version?

**Comment by MrJackSpade** [comment]
Yeah, the reason I ask is because the last time I checked, there was no 64GB image for the 1.1.6 version.

With the layout of the stock image there's 40+ GB of space at the end of the image and the roms directory is actually at the beginning of the image (simplified)

    [roms] [boot] [root_fs] [empty space]
    
 Since you're saying you have ~40Gb on your rom directory, I'm assuming you have
 
     [empty space] [boot] [root_fs] [roms]
     
because AFAIK you can't move the boot.

With the stock image you can literally just expand the root_fs into the empty space at the end of the card if you've flashed a 16GB image over a 64GB card, but since the roms are likely in that space on the modified image, you would likely have to re-partition that part of the card.

Assuming that's the case, I would (back up the card then) move your roms off the rom partition, shrink it, move it towards the end of the card, and then expand the root_fs into the newly created space

That is assuming the roms partition can be shrunk/moved, however in the event that it cant for some reason, you *should* be able to delete and recreate it at a smaller size. IIRC the boot scripts only use the index of the partition for mounting and not the location, so as long as you don't swap the order, it should "just work"

**Comment by kasra9400** [comment]
![photo_2024-09-20_23-39-07](https://github.com/user-attachments/assets/e7863256-331c-40e4-bf6a-0ab19125d5e6)
there is two more partition between the ROMS and root_fs i can't move the partitions to expand the root_fs 
by the way what about important system data on these partitions? 
sorry im new with linux

**Comment by MrJackSpade** [comment]
Have you tried shrinking the roms partition and moving those into the free space? AFAIK the only partition that actually can't be moved is the boot one. The rest can be moved, but not reordered 

If you shrink roms by a few GB you may be able to slide those into the free space, freeing up space for the root fs

**Comment by kasra9400** [comment]
shrink volume option is disabled. but i deleted ROMs partition and have free space but still can't move it or give it to root_fs

**Comment by kasra9400** [comment]
![Screenshot 2024-09-21 003802](https://github.com/user-attachments/assets/b5efc863-b351-4a51-b227-a62275f54108)
these two blocking my way

**Comment by MrJackSpade** [comment]
Shrink might be disabled because its an NTFS volume on linux, which is why I suggested earlier that you may need to delete the partition and recreate it. Linux doesn't have the best NTFS support. 

You're best option is to likely delete the roms, then recreate it at a smaller size, THEN move the two circled partitions on linux

**Comment by kasra9400** [comment]
> Shrink might be disabled because its an NTFS volume on linux, which is why I suggested earlier that you may need to delete the partition and recreate it. Linux doesn't have the best NTFS support.
> 
> You're best option is to likely delete the roms, then recreate it at a smaller size, THEN move the two circled partitions on linux

problem fixed without any issue. 
thanks a lot! ❤️
