### ISSUE TITLE
date: invalid date Failed to set date

### ISSUE THREAD

**Issue by qfertig** [MrJackSpade/RG35XXP-XFCE#20]
Maybe be a noob here at most of this but when I went to install

./install_xfce.sh
Starting
date: invalid date '09 Oct 2024 20:48:07Z'
Failed to set date

I set my time zone and time three different times, at this point not too sure what to do. I set the date via the terminal and through the settings, what am I missing?

**Comment by MrJackSpade** [comment]
Thats really weird.

One of the first things the script does is attempt to set the date, because if the date isn't set correctly it will throw errors when running the install/update scripts.

Thats this line right here:

https://github.com/MrJackSpade/RG35XXP-XFCE/blob/41af51a3b65b589d76862d8cd65097cf9e265db3/install_xfce.sh#L11

And here:

https://github.com/MrJackSpade/RG35XXP-XFCE/blob/41af51a3b65b589d76862d8cd65097cf9e265db3/payload/home/root/setup/run_me.sh#L3

As long as the date on the device is set correctly, you should just be able to delete both of those lines from the files and then run it.

I've never actually seen this line fail before though, what firmware are you installing under?
