### ISSUE TITLE
XFCE freezes once I am on desktop with the chinese message box.

### ISSUE THREAD

**Issue by arand4** [MrJackSpade/RG35XXP-XFCE#21]
As title states, I seemingly installed successfully but when I check the log I see a bunch of errors (log attached). Sorry for my incompetence ;) but I don't quite understand what the underlying issue is. Is it missing space on a different partition?

Thanks in advance.

[XFCE.log](https://github.com/user-attachments/files/17477865/XFCE.log)

**Comment by MrJackSpade** [comment]
It's a two part install process. Did you run the second part, the install script on the desktop after you log in?

**Comment by arand4** [comment]
Thanks for the reply,

Yeah, I saw that, but once I start xfce I can't do anything, the desktop just loads with that message box and I can't move the cursor and even to exit back to the home screen of the Anbernic I have to hard reset the device.

**Comment by MrJackSpade** [comment]
What firmware version and can you attach an image of the message box?

**Comment by arand4** [comment]
I'm on stock version atm, v1.0.3 (20240511)
I assume this should work on my slightly outdated firmware, as the instructions on here didn't mention that there could be compatibility issues if I have an older version, but I do agree I should probably update to the latest version that you support.

According to my OCR this is this popup message is part of a setup.
![IMG_1768](https://github.com/user-attachments/assets/c2d05ec9-379a-4d7b-879d-1858ef9d4971)

**Comment by MrJackSpade** [comment]
Oh, yeah. The older firmware version is almost certainly the problem. They made huge changes to the OS at some point between the initial release I did (around that time) and the newest 1.1.6 when I rewrote most of the code.

Like the partitions changed, the underlying architecture of the OS changed, the filesystem changed. 

I hadn't put a note in because I haven't had the opportunity to actually test how far back it works, but I can almost guarantee thats your issue.

**Comment by arand4** [comment]
Ok, I will update the firmware tomorrow and try again.
I guess I tested for you that at least on v1.0.3 it pretty certainly doesn't work, I'm surprised though how far the installation came if so much has changed.

**Comment by arand4** [comment]
Well, I updated the firmware, I ended up installing the Stock OS Modification by cbepx-me cause I couldn't find anyone with the 64GB Image, and didn't want to contact anbernic's customer support for a link of that as it probably would take another day.
But well, I was able to successfully install xfce this time.

**Comment by JazzJohannes** [comment]
> Well, I updated the firmware, I ended up installing the Stock OS Modification by cbepx-me cause I couldn't find anyone with the 64GB Image, and didn't want to contact anbernic's customer support for a link of that as it probably would take another day. But well, I was able to successfully install xfce this time.

Works here too, just installed it! Make sure when you use QJoycon to map the joystick correctly, that you change where it first mentions mouse you have to set either vertical mouse or horizontal mouse on each adjacent button, and make sure the mouse speed is corrected to 2 or 3. I have set the A button to be a mouse click too, although L1 by default is also good.

Be careful when you install AdGuard, don't click to many times at once because you thought it didn't register. It did register, it just opens the tabs after a bit and ALL of them, rendering it almost impossible to close again.

And btw finally PORTMASTER on STOCK!!!! hihihihihi Or so I think, hopefully it'll work hihihihi
