### ISSUE TITLE
Incorporate Joycons and Peripheral QJoypad Support

### ISSUE THREAD

**Issue by LuckyTechnology** [MrJackSpade/RG35XXP-XFCE#32]
Many users may not have a usb mouse and keyboard. It would be amazing to set up a default working system Peripherals Joycons support. Filename: Default.lyt

I set up the JoyCon and Peripheral support.
I set Select button to Mouse Left Click also
I set Start button to Mouse Right Click also

# QJoyPad 4.3 Layout File

Joystick 1 {
	Axis 1: gradient, maxSpeed 2, mouse+h
	Axis 2: gradient, maxSpeed 2, mouse+v
	Axis 3: gradient, maxSpeed 2, mouse+h
	Axis 4: gradient, maxSpeed 2, mouse+v
	Axis 5: gradient, maxSpeed 2, mouse+h
	Axis 6: gradient, maxSpeed 2, mouse+v
	Button 5: mouse 1
	Button 6: mouse 3
	Button 7: mouse 1
	Button 8: mouse 3
}

**Comment by MrJackSpade** [comment]
Joycon like Nintendo Switch joycons?

Or joystick like an arcade joystick?

I'm not intending on overwriting the default file, however if you want to properly name this something like "Joystick.lyt" or whatever clearly expresses its intent and merge it in as an option, that is fine.

The qjoypad profile can be swapped without needing a mouse and keyboard, it just cant be modified because opening the edit window disables the active profile. Multiple profiles work fine though.

**Comment by LuckyTechnology** [comment]
The default file. It didn't work properly. I had to manually set it up to have the device joycons working. Not the Nintendo Switch.

"The qjoypad profile can be swapped without needing a mouse and keyboard."
Oh really. I'll try to figure that out. Thank you

Default
Joystick 1 {
	Axis 4: gradient, maxSpeed 2, mouse+h
	Axis 5: gradient, maxSpeed 2, mouse+v
	Button 5: mouse 1
	Button 6: mouse 3
	Button 10: mouse 5
	Button 11: mouse 4
}

**Comment by MrJackSpade** [comment]
What device specifically are you using? If the file doesn't work it might be an incompatibility with the existing settings and your device, which should probably be accounted for during installation
