### ISSUE TITLE
Does this can run on rg40xx h ?

### ISSUE THREAD

**Issue by VyTung** [MrJackSpade/RG35XXP-XFCE#38]
Does XFCE can run on rg40xx h ? .I know it is same with rg35xx h but , i just ask before i buy the rg40xx h. Thank you

**Comment by MrJackSpade** [comment]
It **should**.

[One person reported it as non-working](https://github.com/MrJackSpade/RG35XXP-XFCE/issues/24) but I was unable to follow up and determine if it was a failure on their part.

If it doesn't work, I assume its something stupid, and I sure as hell cant think of how they ended up with lines on their screen after installing it.

Unfortunately I don't have a way to be sure either way. At this point it seems more likely that it was a one-off error that prevented it from running because as you said its literally the exact same as the 35XXH.

**Comment by VyTung** [comment]
i just saw some1 said the vertical lines error on rg40xx h is cuz the screen gpu driver is not the same with rg35xxh . so do u know how to change the screen gpu driver of XFCE ?

**Comment by VyTung** [comment]
> It **should**.
> 
> [One person reported it as non-working](https://github.com/MrJackSpade/RG35XXP-XFCE/issues/24) but I was unable to follow up and determine if it was a failure on their part.
> 
> If it doesn't work, I assume its something stupid, and I sure as hell cant think of how they ended up with lines on their screen after installing it.
> 
> Unfortunately I don't have a way to be sure either way. At this point it seems more likely that it was a one-off error that prevented it from running because as you said its literally the exact same as the 35XXH.
i just saw some1 said the vertical lines error on rg40xx h is cuz the screen gpu driver is not the same with rg35xxh . so do u know how to change the screen gpu driver of XFCE ?

**Comment by VyTung** [comment]
i just saw some1 said the vertical lines error on rg40xx h is cuz the screen gpu driver is not the same with rg35xxh . so do u know how to change the screen gpu driver of XFCE ?

**Comment by VyTung** [comment]
or can u teach me how to make XFCE like code it run on the device ? XD maybe this is dumb question...

**Comment by MrJackSpade** [comment]
I don't know why the GPU driver would be different, it uses the exact same GPU.

Also, this installer doesn't come with a GPU driver or leverage any functionality around the GPU driver at all either way. The only files packaged in this repository are configuration files for the desktop environment. There are no executable or drivers included in this, it simply downloads/installs/configures the system packages required to get this all running.

So even if it was a different GPU driver, I can't think of any reason that would affect the results of this script in any way, since its not driver dependent.

**Comment by VyTung** [comment]
hmm welp.. im gonna buy the rg40xx h in next year and test it out

**Comment by MrJackSpade** [comment]
Let me know how it goes and if you run into any issues we can attempt to resolve them
