### ISSUE TITLE
Remapping and Sound Problems

### ISSUE THREAD

**Issue by yolo9572** [MrJackSpade/RG35XXP-XFCE#39]
I couldn't quite get my mouse buttons to move on my anbernic RG35XXH, the left D-PAD is used for the x-axis, and weirdly enough the right joystick is used for the y-axis. I could really use some help, 
Thanks!

**Comment by MrJackSpade** [comment]
The easiest way to resolve it is to use a regular mouse to open qjoypad and click the buttons to remap.

If thats not an option, another used had a similar issue and posted a qjoypad profile

https://github.com/MrJackSpade/RG35XXP-XFCE/issues/33

I can't speak to how well it works since I don't have an RG35XXH to test with

**Comment by yolo9572** [comment]
Thanks for the help, I will test it out and report my findings!
Just one last question, any idea on the sound. I can't get anything to play with sound on youtube or any other website.
Thanks again!

**Comment by MrJackSpade** [comment]
Is the speaker icon on the taskbar not accessible? You should be able to change the output pipe using that icon

**Comment by yolo9572** [comment]
Once I click on the speaker icon it opens up a new window. Once on that window an infinitely loading screen appears that says "Establishing connection to PulseAudio. please wait..."
Any ideas?

**Comment by MrJackSpade** [comment]
How long ago did you pull down the code? There were a few audio issues that were resolved a few weeks ago.

If you pulled recently then its probably something else, but if you pulled a few weeks ago and didn't try until now, that should be it.

If your pull was recent, I would recommend restarting first and then going straight into XFCE to start, and checking to see if it works. The pulse audio server is one of the biggest PITA about this setup and it likes to just randomly stop working, but usually a restart fixes it. 

If that's not it, the best thing I can think would be for you to copy your internal memory and upload it somewhere so I can debug it locally and see if I can find the root cause, since otherwise I would have to try and walk you through a bunch of steps and that would take a while.

Simply restarting the pulse audio server should work but that doesn't address the root cause of why its not starting/failing on its own.

**Comment by yolo9572** [comment]
I'm currently deleting the entire file from my SD card and starting over with my custom code for the remapping from "LuckyTechnology" through the fork I made. Maybe by redoing the entire process it would reset the system as you talked about. Once it's finished I'll report back and update you on what's happening.

**Comment by MrJackSpade** [comment]
That should certainly do it. Just make sure you have a fresh pull of everything.

**Comment by yolo9572** [comment]
Ok, currently in the process of finishing up, does wifi have anything to do with the PulseAudio loading?

**Comment by MrJackSpade** [comment]
It shouldn't, but I have seen stranger things.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yolo9572** [comment]
Thanks so much for the help on remapping, It's working flawlessly with all three sets of buttons controlling the mouse (D-PAD, JOYSTICK1, and JOYSTICK2). Although I can only hear cracking from the speakers even if there is no volume playing. But the mouse finally works perfectly.

**Comment by MrJackSpade** [comment]
Well that's certainly a start. Is the pulse audio service connecting now?

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yolo9572** [comment]
Nope, can't connect it whatsoever.

**Comment by MrJackSpade** [comment]
Could you take a disk image and upload it somewhere for me, or I can give
you somewhere to upload it?

I would like to run it locally and see what happens

**Comment by yolo9572** [comment]
You mean my SD card ISO for the amberic RG35XXH with the RG35XXP-XFCE app on it?

**Comment by yolo9572** [comment]
It seems that I can't send anything on Github that's over 25MB, would you like me to upload it through a Google Drive?

**Comment by MrJackSpade** [comment]
That would work great.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yolo9572** [comment]
https://drive.google.com/drive/folders/1QedYETeS8wB5eshFUc54ujWvOmqln0EN?usp=drive_link

**Comment by MrJackSpade** [comment]
Access requested.

**Comment by yolo9572** [comment]
OK

**Comment by MrJackSpade** [comment]
I need an actual img of the sd card (TF1), do you know how to take one?

**Comment by yolo9572** [comment]
I've done it before with Rufus. But I've never uploaded it to the web, only to my SD card.

**Comment by yolo9572** [comment]
I'm currently on a Chromebook, but have an IMG. of the AmbernicRG35XXH firmware on my windows computer. Is that what you want?

**Comment by MrJackSpade** [comment]
What I need specifically is for you to take a new image of your card after
XFCE has been installed, and then upload that image.

I will then take that image and flash it to my SD card and use that to
figure out whats going on with the sound. Once I figure that out, I can
send you a script to correct the issue, and integrate that fix into the
source code so that it doesn't affect other people in the future.

Fortunately/Unfortunately when I run the installer myself, I don't have
issues with the sound, so I have no way if figuring out whats gone wrong
without the image.

**Comment by yolo9572** [comment]
Ok, I'm currently uploading my entire SD card to MEGA. Then I will give you the link, sounds good?

**Comment by MrJackSpade** [comment]
That sounds good to me. I will remove the link from this issue (if
possible) once I have downloaded the image, and will hopefully have a
resolution before the end of the weekend

**Comment by yolo9572** [comment]
Ok, thanks for the help!

**Comment by yolo9572** [comment]
Do you believe that updating my firmware for the RG35XXH would fix it, Its currently two updates behind but I don't know if it will make too much of a difference. (Also Ill upload the IMG file tomorrow, there are too many errors happening and I'll try to do it through the app and not the website.)

**Comment by MrJackSpade** [comment]
It might, but I don't think it would. If you're two updates behind that
puts you on 1.1.6, and I don't think anything has substantially changed
since then. Its probably a good place to start though.

**Comment by yolo9572** [comment]
Ok, Ill update the files in the morning. Thanks for your help so far!

**Comment by yolo9572** [comment]
https://we.tl/t-vtAT0hHy89

**Comment by yolo9572** [comment]
That's the link to my SD card, it expires in three days so if you need me to "renew" it I can

**Comment by MrJackSpade** [comment]
I'm downloading it, but this isn't just a folder of the SD card content
right? It says 11K items, it should only be one item, a single .IMG file

https://www.makeuseof.com/tag/create-image-usb-drive/

**Comment by yolo9572** [comment]
Understood, I will have it done as soon as possible!

**Comment by yolo9572** [comment]
While using the ImageUSB application (that took over 5 HOURS to complete) I ran into two problems: 
1) No ISO file was created
2) The .Bin file produced is 119 GB, so way too much to transfer online.

**Comment by yolo9572** [comment]
I'm going to try to update my ambernic. After looking into it I found out I was on V1.1.6 and thought it was time for an update, maybe that would fix the problem. This may be a stupid question but even if I use a two card setup, could I still save my data like my states, my favorites, and settings?

**Comment by MrJackSpade** [comment]
You're creating an image of TF1 and not TF2 right?

Also bin is fine, it's raw binary file so bin or img is expected. ISO is CD.

If you're imaging TF1 the file should zip to 2-4gb

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yolo9572** [comment]
Yes I'm making a image of the TF1 card. But there are no FREE file sharing services that allow 119GB transfers. Is there any other way to send you the .bin file?

**Comment by MrJackSpade** [comment]
Start by zipping it and seeing how much the size reduces. It should be mostly empty space

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yolo9572** [comment]
It reduced to 22GB, I'm using dropbox to upload it, Ill send the link as soon as possible.

**Comment by yolo9572** [comment]
https://www.dropbox.com/scl/fi/t723qakgs7t2j5n7ba7pg/AMBERNICRG35XXH.zip?rlkey=essyjy2zxxt4y8438chqn3zai&st=6od3zyyf&dl=0

**Comment by MrJackSpade** [comment]
Downloading now

**Comment by MrJackSpade** [comment]
I've removed the link to prevent it from being scraped or abused. I will try and flash it hopefully tomorrow and see if I can figure out the issue

**Comment by yolo9572** [comment]
OK, thanks!

**Comment by yolo9572** [comment]
When you ran the Ambernic, did you find any sound issues?

**Comment by MrJackSpade** [comment]
Haven't checked yet. Finishing up with work, will reply later

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yolo9572** [comment]
Ok, all good!

**Comment by MrJackSpade** [comment]
After some headache, I managed to get the image flashed and can confirm the lack of sound.

**Comment by yolo9572** [comment]
Well, at least I know I'm not crazy. Do you hear crackling when the RG35XXP-XFCE application is opened? Because that's what I've experienced while using it.

**Comment by MrJackSpade** [comment]
What firmware is this? 

You appear to have an entire separate GNOME desktop installation in here that may be conflicting with the XFCE stuff

**Comment by yolo9572** [comment]
I've tried different kinds of desktop applications and found this one to be my favorite. Although I thought I've deleted them already.

**Comment by MrJackSpade** [comment]
I would strongly advise starting from a 1.1.8 base and then only installing
XFCE (or at least, installing it first). The other lingering system changes
are very likely conflicting with the XFCE settings.

It looks like the audio service is running but the applet cant connect to
it, and there are potentially permissions and such missing, which may be
the result of setup commands failing due to the existing modifications to
the system.

**Comment by yolo9572** [comment]
When I update, could I save my settings?

**Comment by MrJackSpade** [comment]
You can export/import your retroarch settings (I don't know how but I know
you can) but not the system settings. Its just a general failure with how
Anbernic does their system updates.

**Comment by yolo9572** [comment]
Ok, if I have a 2 card setup would that change anything, or it it the same thing. The reason I'm so worried about this is because when I reset last time, my Anbernic settings were completely wiped (Favorites, time, etc...). Also would I just save RETROARCH.CFG to my computer, then write a new IMG onto the SD and add them back (and then of course the XFCE)?

**Comment by MrJackSpade** [comment]
If you're worried about it, I would just make sure you keep that IMG file
you sent me. It has everything saved on it. If theres anything missing you
can revert using that image file

**Comment by yolo9572** [comment]
Ok, I just don't want to mess with too much and potentially screw anything up. For example I have no idea on how Retroarch updates affect/change the .cfg files but if I were to use old configuration files it could maybe mess it up and I'm sorta half decent at fixing things on the Ambernic but I just am too unfamiliar with Retroarch. Although, as you said, I do have an extra copy of the .IMG so nothing could go wrong and even if I mess something up I could just start over. I'll try to update It tomorrow afternoon and see what happens.

**Comment by yolo9572** [comment]
Ok, good and bad news. First the good, after updating the Ambernic and re-installing the XFCE app the sound menu finally works. But now the bad news, STILL no sound. I'll continue experimenting because now I can at least adjust the (not working) sound, but it's still a step in the right direction!

**Comment by MrJackSpade** [comment]
If the MENU works, then it should be as simple as switching the output device.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yolo9572** [comment]
Yes, so once I switched it, audio worked, but now, NO audio is coming from any other game on the Ambernic other than the XFCE app.

**Comment by MrJackSpade** [comment]
Does switching the audio sink back, make the audio start coming out again?

Does restarting make the audio start coming out again?

Does the audio not work in both retroarch, AND apps like the music player?

**Comment by yolo9572** [comment]
1) No
2) No
3) It's confusing, in any app other than XFCE it wont work. In retroarch it won't work. BUT, in the main Ambernic emulators it works.

**Comment by MrJackSpade** [comment]
I'm pretty sure retroarch can be fixed by switching the audio output device
(to pulse?) though you have to restart retroarch for the settings to take
effect. It won't apply the audio setting change unless you actually close
and reopen the app.

I have no idea what's going on with the other apps though, the last time I
installed everything it worked without any other issues. The last few
check-ins are specifically around correcting the audio issues.

**Comment by MrJackSpade** [comment]
I have confirmed that audio WILL work in retro-arch as long as you select the SDL2 output for audio.

I will have to look into the other apps.

Theres clearly some fundamental difference between the audio setup on the + and the H versions of the device. I'm probably going to have to modify the installer to detect the specific firmware and install differently with each device.

**Comment by yolo9572** [comment]
Ok, so if you turn off and then back on audio, then it will work but it gets quite annoying after some time. And I still cant get any audio from the music/video app.

**Comment by MrJackSpade** [comment]
I'm going to look into it, I'm just burnt out AF right now.

With the RG35XX+ the issue you're seeing was caused by a specific
configuration file included with the system image, that was unused. The
configuration looked for Pulse Audio and then attempted to route all audio
through Pulse if it existed, but on the stock installation Pulse doesn't
exist so the configuration never actually did anything.

When installing Pulse Audio the configuration gets loaded, and attempts to
route all audio through it, but because it was never *intended* to
function, it doesn't actually work, which caused the entire audio system to
fail (outside XFCE) the second Pulse was installed.

The solution was to simply delete the "unused" configuration file (or
something along those lines?)

I'm looking at the actual source code now though and I actually don't see
any references to that file, so now I'm wondering if maybe its simply a
regression, or if my dumb ass just forgot to check the change in...

**Comment by MrJackSpade** [comment]
I found the file and I think I have a fix. Do you have a windows or Linux machine? If you have Linux I can give you a simple fix right now, otherwise you'll have to wait for me to build/test/deploy and then reinstall.

The solution is just to comment out a file

**Comment by yolo9572** [comment]
I have a windows computer, what exactly would you like me to do?

**Comment by MrJackSpade** [comment]
Weird... My last post didn't show up.

I've corrected the installer, but you don't actually need to reinstall for the fix. You also don't need to use your computer since you can do it directly on-device, it would just be easier if you had linux since the linuxfs would mount.

Just open XFCE and open the file browser, then open the file 

```
/usr/share/alsa/alsa.conf.d/pulse.conf
```

And delete all of the text out of it. **Do not delete the file**. Just delete the text out of it so its empty, and then restart.

This is the "configuration" I remembered that I referenced above, the one that isn't even supposed to be used by the stock system, but causes the audio to break once pulse is installed. 

Once you edit it and restart, all of the audio in every app should work. 

I have no idea how I went through all of this already and the fix seemingly never made it into the code, but its there now.

**Comment by yolo9572** [comment]
Wow, I can't thank you enough! As of now everything works flawlessly, and Retroarch sound works without entering settings every time. I would just like to thank you so much for your patience throughout TWO WEEKS and SIXTY-FIVE comments!

**Comment by MrJackSpade** [comment]
Glad we could finally get to the root of it, and now the issue will be fixed for everyone else moving forward
