### ISSUE TITLE
Installation error: Failed to get system time

### ISSUE THREAD

**Issue by AdamMat2** [MrJackSpade/RG35XXP-XFCE#44]
Failed to get system time: The request was canceled due to the unconfigured HttPClient.Timeout of 100 seconds elapsing.
     at RG35XX.Libraries.Utilities.CorrectSystemTime()
     at RG35XX_XFCE.Program.Main(String[]) in D:\Git\RG35XXP-XFCE\Program.cs:line147

The steps I took leading to this error were:

1. flashing my Kioxia 64G sd card with latest stock 1.1.8 straight from Anbernic's website (https://win.anbernic.com/download/360.html) and inserting it into my RG35XX-H through the TF1/INT slot using rufus with default settings.

2. Downloading "RG35XX-XFCE" from this github page and the "Payload" file from the site https://download-directory.github.io/ by giving it the file's web address (https://github.com/MrJackSpade/RG35XXP-XFCE/tree/main/payload).

3. Putting both on G:\Roms\APPS as shown here: https://github.com/user-attachments/assets/e851b02e-e352-467f-a0f1-3e3b456cf2c0

4. Connecting to my internet with a password, checking the date is correct (it is, 2024/12/27) and opening "App Center', "APPS", "TF01" and then finally "RG35XX-XFCE". The error appeared after a few minutes of an awesome dance session in a red color on top of the screen.

After getting this error I tried the appstore installation too (https://github.com/MrJackSpade/RG35XX-Store/blob/main/AppStore/Release/AppStore) and I got a similiar error:

The request was canceled due to the configured HttPClient.Timeout of 100 seconds elapsing.
at System.Net.HttP.HttpClient.HandleFailure(Exception, Boolean, HttPResponseMessage, CancellationToken, CancellationTokenSource)
at System.Net.HttP.HttPClient.GetStringAsYncCore(HttPRequestMessage, CancellationToken)
at APPStore.Store.Execute() in D:\Git\RG35XX_Store\Store.cs:line 47

Hopefully you can help me resolve this issue with these detailed steps, sorry if it was too much. I would really like to get this working, I think this is a cool project!

**Comment by MrJackSpade** [comment]
So that block of code attempts to connect to www.google.com and use the header information to ensure the system time is correct, otherwise the SSL cert check will fail and the packages will fail to install.

Can you think of any reason why you may fail to connect to www.google.com on your internet?

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: AdamMat2 ***@***.***>
Sent: Friday, December 27, 2024 10:32:13 AM
To: MrJackSpade/RG35XXP-XFCE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MrJackSpade/RG35XXP-XFCE] Installation error: Failed to get system time #41 (Issue #44)


Failed to get system time: The request was canceled due to the unconfigured HttPClient.Timeout of 100 seconds elapsing.
at RG35XX.Libraries.Utilities.CorrectSystemTime()
at RG35XX_XFCE.Program.Main(String[]) in D:\Git\RG35XXP-XFCE\Program.cs:line147

The steps I took leading to this error were:

  1.  flashing my Kioxia 64G sd card with latest stock 1.1.8 straight from Anbernic's website (https://win.anbernic.com/download/360.html) and inserting it into my RG35XX-H through the TF1/INT slot using rufus with default settings.

  2.  Downloading "RG35XX-XFCE" from this github page and the "Payload" file from the site https://download-directory.github.io/ by giving it the file's web address (https://github.com/MrJackSpade/RG35XXP-XFCE/tree/main/payload).

  3.  Putting both on G:\Roms\APPS as shown here: https://github.com/user-attachments/assets/e851b02e-e352-467f-a0f1-3e3b456cf2c0

  4.  Connecting to my internet with a password, checking the date is correct (it is, 2024/12/15) and opening "App Center', "APPS", "TF01" and then finally "RG35XX-XFCE". The error appeared after a few minutes of an awesome dance session in a red color on top of the screen.

After getting this error I tried the appstore installation too (https://github.com/MrJackSpade/RG35XX-Store/blob/main/AppStore/Release/AppStore) and I got a similiar error:

The request was canceled due to the configured HttPClient.Timeout of 100 seconds elapsing.
at System.Net.HttP.HttpClient.HandleFailure(Exception, Boolean, HttPResponseMessage, CancellationToken, CancellationTokenSource)
at System.Net.HttP.HttPClient.GetStringAsYncCore(HttPRequestMessage, CancellationToken)
at APPStore.Store.Execute() in D:\Git\RG35XX_Store\Store.cs:line 47

Hopefully you can help me resolve this issue with these detailed steps, sorry if it was too much. I would really like to get this working, I think this is a cool project!

**Comment by AdamMat2** [comment]
No idea to be honest. I am connected to the same internet on my computer and I have no such problem. I'll try it again with public wifi when I'm outdoors, maybe that'll work.

**Comment by AdamMat2** [comment]
Tried it again today and it worked. Hooray. Looking forward to playing with this, thank you for your work :)
